Test title subtitle pagetitle xg
Iostream3100/Studio-Web pull request #34
Opened 2022-10-26 18:09 UTC by guanxiaotongyz

2022-10-27 21:26 UTC, Iostream3100 commented on src/app/demo/demo.component.spec.ts
> +  let component: DemoComponent;
Please put all the tests for this DemoComponent into one `describe` function for readability.

2022-10-27 22:10 UTC, Iostream3100 commented
Good job!
Please follow the recommendations of Conventional Commits https://www.conventionalcommits.org/ as much as possible in our projects, like "feat: implement a nav-bar"

2022-10-27 22:11 UTC, Iostream3100 commented
Please test the latest version(with input component) of the demo page, you can pull from the `editable_titles` branch.

2022-10-27 22:12 UTC, Iostream3100 requested changes
Please test the latest version(with input component) of the demo page, you can pull from the editable_titles branch.

2022-11-02 19:32 UTC, crystaljesica commented
Please see those conflict files, you may need to git pull from the repo to get the latest file and make changes based on those.

2022-11-08 22:44 UTC, closed without merging