Test editable page title wmd
Iostream3100/Studio-Web pull request #39
Opened 2022-10-27 07:56 UTC by crystaljesica

2022-10-27 21:04 UTC, Iostream3100 commented on src/app/demo/demo.component.spec.ts
> +  let component: DemoComponent;
It might be more readable to put all the tests inside one describe() function.

2022-10-27 21:07 UTC, Iostream3100 requested changes
Good job!
Please follow the recommendations of Conventional Commits https://www.conventionalcommits.org/ as much as possible in our projects, like "feat: implement a nav-bar"

2022-10-31 17:01 UTC, Iostream3100 approved these changes
Great Job.
The code is very clear.

2022-10-31 17:25 UTC, yoxchen95 approved these changes

2022-10-31 17:34 UTC, guanxiaotongyz approved these changes

2022-10-31 19:23 UTC, merged